### ISSUE TITLE
Error in lib/connector.js dependencies

### ISSUE THREAD

**Issue by norx85** [adityamukho/node-box-sdk#3]
When i try to use your module i get the following error:

[...]\node_modules\box-sdk\lib\connector.js:403
Monologue.mixin(Connection);
          ^
TypeError: Cannot call method 'mixin' of undefined
    at Object.<anonymous> (e:\Projects\prmc\node_modules\box-sdk\lib\connector.js:403:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (e:\Projects\prmc\node_modules\box-sdk\lib\box-sdk.js:32:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

I think that problem is in the requirements: 
Monologue = require('monologue.js')(_)

thath probably can be changed just in
Monologue = require('monologue.js')

**Comment by adityamukho** [comment]
The Monologue version used in this SDK (0.1.4) exports a function that must be called with a (optional) reference to `underscore` (or equivalent ) before it can be used. At least that is how it is meant to be invoked in CommonJS-like environments (incl. `node.js`). In fact, if I run the test suite with just `Monologue = require('monologue.js')` it throws an error since it can't find the method `mixin` in the exported function prototype.

Could you please take a fresh checkout of the SDK, run the test suite and see if you get the same error? Also, please ensure that the SDK version used in your project is the latest.

**Comment by norx85** [comment]
Yes i'm getting the same error

**Comment by norx85** [comment]
I see 0.1.4 in your package.json, but "npm install" ignore it and install the 0.3.0 version of monologue. 
i'm using nodejs 0.10.13 bundled with npm 1.3.2.
Probably I can force the install of the correct version locally, but my production environment is on the cloud, so installation is done automatically by the provider
